# Site settings
title: Fabio Filli
email: hejhej@fabiofilli.com
description: > # its just the personal website and blog of fabio filli.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hejhej.fabiofilli.com" # the base hostname & protocol for your site
twitter_username: fabiofilli
github_username:  fabiofilli

# Build settings
markdown: kramdown

permalink: /:title/

defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: posts
      lang: en
  -
    scope:
      path: _posts/de
    values:
      layout: posts
      lang: de
